export const theme = {
  fonts: {
    titleLarge: {
      lineHeight: 28,
      fontSize: 22,
      letterSpacing: 0,
      weight: '400',
    },
    labelLarge: {
      lineHeight: 20,
      fontSize: 14,
      letterSpacing: 0.1,
      weight: '500',
    },
    bodyLarge: {
      lineHeight: 24,
      fontSize: 16,
      letterSpacing: 0.5,
      weight: '400',
    },
    bodyMedium: {
      lineHeight: 20,
      fontSize: 14,
      letterSpacing: 0.25,
      weight: '400',
    },
    headlineSmall: {
      lineHeight: 32,
      fontSize: 24,
      letterSpacing: 0,
      weight: '400',
    },
    headlineLarge: {
      lineHeight: 40,
      fontSize: 32,
      letterSpacing: 0,
      weight: '400',
    },
  },
  spaces: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
  },
  colors: {
    background: '#fff',
    onBackground: '#000',
    surface: '#fff',
    onSurface: '#000',
    surfaceVariant: '#e5e6e6',
    onSurfaceVariant: '#4c4d4d',
    outline: '#7d8282',
    outlineVariant: '#cbcdcd',
    primary: '#304f9c',
    onPrimary: '#ffffff',
    primaryContainer: '#d8e0f3',
    onPrimaryContainer: '#0c1427',
    secondary: '#00b2ce',
    onSecondary: '#ffffff',
    secondaryContainer: '#ccf8ff',
    onSecondaryContainer: '#002c33',
    error: '#c10e0b',
    onError: '#ffffff',
    errorContainer: '#fcd0cf',
    onErrorContainer: '#300403',
    opacity: (percent: number) => ({
      primary: `rgba(48, 79, 156, ${percent})`,
      onSurface: `rgba(9, 5, 46, ${percent})`,
    }),
  },
  elevations: {
    1: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.15,
      shadowRadius: 1.0,
      elevation: 1,
    },
    2: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.16,
      shadowRadius: 1.51,
      elevation: 2,
    },
    3: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.17,
      shadowRadius: 2.54,
      elevation: 3,
    },
    24: {
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 18,
      },
      shadowOpacity: 0.25,
      shadowRadius: 20.0,
      elevation: 24,
    },
  },
  modal: {
    borderRadius: 28,
    minWidth: 280,
    maxWidth: 560,
    padding: 24,
    margin: 24,
  },
} as const;
